---
title: "Course Syllabus"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      comment = "")
```

Last Updated: `r format(Sys.Date(), "%m/%d/%Y")`

# Course Title {#title}

PSY:3170 – Fantasy Football: Predictive Analytics and Empiricism (Fall 2025)

# Course Meeting Time and Place {#lectureTime}

Tuesday and Thursday 11:00 a.m. – 12:15 p.m., 158 Van Allen (VAN)

# Course Website {#website}

https://icon.uiowa.edu

To access the course site, log into [Iowa Courses Online (ICON)](https://icon.uiowa.edu) using your Hawk ID and password.

# Course Home {#home}

The College of Liberal Arts and Sciences (CLAS) is the home of this course, and CLAS governs the add and drop deadlines, academic misconduct policies, and other policies and procedures.
Other UI colleges may have different policies.

# Instructor Contact Information {#instructor}

[Professor Petersen](https://psychology.uiowa.edu/people/isaac-petersen)\
Office: 175 Psychological and Brain Sciences Building (PBSB)\
E-mail: [isaac-t-petersen@uiowa.edu](mailto:isaac-t-petersen@uiowa.edu)\
Office Phone: 467-1014\
Student drop-in hours: <mark>INSERT</mark>\
Note: I'm here to help you learn and succeed.
Please come to my office hours to ask questions about course material, assignments, exams, or professional development (career-related issues), for instance.
I welcome you to discuss any concerns you might have about the class.
I am also available to meet with you by appointment, although I would appreciate your making every effort to see me during office hours.
The best way to reach me outside of class is by email.

# Departmental Resources {#deptResources}

Department of Psychological and Brain Sciences: [https://psychology.uiowa.edu](https://psychology.uiowa.edu)\
Department of Psychological and Brain Sciences Main Office: G60 Psychological and Brain Sciences Building (335-2406)\
Coordinator of Undergraduate Studies: Professor Windschitl ([paul-windschitl@uiowa.edu](mailto:paul-windschitl@uiowa.edu); 335-3681)\
Academic Coordinator: Janeil Page-Jamison ([janeil-page@uiowa.edu](mailto:janeil-page@uiowa.edu); 384-3657)\
Chair of Department: Professor Blumberg ([mark-blumberg@uiowa.edu](mailto:mark-blumberg@uiowa.edu); 335-2424)

# Prerequisites {#prereqs}

The Department of Psychological and Brain Sciences has a hierarchical course structure that requires students to complete certain prerequisite courses before taking upper-level courses.
This course requires successful completion (C- or higher) of any of the following statistics courses (or AP Statistics from high school):
PSY 2811, PSQF 1020, PSQF 4143, STAT 1010, STAT 1015, STAT 1020, STAT 1030, STAT 3510, STAT 4143.
The department will check student records to ensure completion of course prerequisites.

# Description of Course {#description}

How can we use information to make predictions about uncertain events?
This course is about empiricism (basing theories on observed data) and judgment, prediction, and decision making in the context of uncertainty.
Students will be introduced to modern analytical techniques used to make informed predictions, test theories, and draw conclusions from a given dataset.
But this is no ordinary course...

Rather than memorizing these empirical approaches in abstraction, students will employ these methods in the active, immersive, hands-on learning laboratory of Fantasy Football.
In this way, the course will weave together two contiguous threads: an introductory overview of data analysis techniques, and a captivating application of these techniques through a semester-long experience in Fantasy Football with their classmates.[^adapted]

The class involves reading primary source material, applying statistical programming (using `R` software), conducting data analysis, and composing written work on a weekly basis.

To be clear, <u>this is a statistics and empiricism course</u>.
It merely uses fantasy football as a lens and application through which to learn about statistics and empiricism.
The class does not assume that students know anything about (or care about) football or fantasy football.
The class is welcome to all, assuming the student meets the prerequisites and that they are interested in learning about empiricism (basing theories on observed data), statistics, and judgment, prediction, and decision making in the context of uncertainty.

Take this class if:

- you want to learn more advanced skills in 1) empiricism, 2) statistics, 3) programming (using `R` software), and 4) judgment, prediction, and decision making in the context of uncertainty;
- you are interested in learning statistics through the lens of a fun sports domain (fantasy football); or
- you are interested in applying psychological and statistical concepts to fantasy football, to gain a strong understanding of critical thinking and decision making in sports.

*Do not take this class if*:

- you are just looking for an "easy" class (the class is not easy);
- you are reluctant to examine fantasy football topics in a scientific manner;
- you do not want to write public blog articles as part of the class; or
- you do not want to learn statistics and programming, and do not want to persist through inevitable challenges along the way.

[^adapted]:
    Elements of this syllabus and course were borrowed and adapted (with permission) from a similar course by Benjamin Motz.

## What is Fantasy Football? And Why Focus on Fantasy Football? {#fantasyFootball}

Fantasy football is an online game where participants assemble (i.e., "draft") imaginary teams composed of real-life National Football League (NFL) players.
In the game of fantasy football, participants compete against others, accumulating "fantasy" points based on players' actual statistical performances in games (and the goal is to outscore one’s opponent each week to win matches and ultimately claim victory in the league).
Fantasy football relies heavily on prediction—trying to predict which players will perform best and selecting them accordingly.
In this way, fantasy football provides a plethora of decision making opportunities in the face of uncertainty, and a wealth of data for analyzing these decisions.
However, unlike many other applied domains in psychology, fantasy football (1) allows a person to see the accuracy of their predictions on a timely basis and (2) provides a safe environment for friendly competition.
Thus, it provides a unique domain to evaluate—and improve—the accuracy of various prediction models.

# Learning Objectives {#objectives}

By the end of the course, successful students will be able to:

- Apply empirical inference and appreciate the value it provides over speculative supposition.
- Ask educated questions when confronted with decisions in the face of uncertainty.
- Understand human decision making, including common heuristics and cognitive biases and how to mitigate them analytically.
- Engage in critical thinking about causality, including devising plausible alternative explanations for observed effects.
- Understand causal inference including confounding, causal pathways, and counterfactuals.
- Think empirically about human behavior and performance.
- Describe the strengths and weaknesses of humans versus computers in prediction scenarios.
- Apply basic skills in statistical programming using `R` to manipulate and summarize datasets and to conduct data analysis.
- Critically evaluate the strengths and limitations of different statistical models and methodologies used in predicting uncertain events, enhancing their understanding of statistical inference and model selection.
- Use various analytical techniques for predicting the outcome of uncertain events, and for uncovering latent causes of patterns in observed data.
- Interpret findings from various statistical approaches and evaluate the accuracy of predictions.
- Engage in iterative problem-solving processes, refining analytical approaches based on feedback and outcomes, and adapting strategies accordingly.
- Communicate statistical findings and analyses in both written and oral formats, demonstrating proficiency in presenting complex information to diverse audiences.
- Make sense of big data.
- Use practical analytical skills that can be applied in future research and job settings.

# Textbook {#textbook}

The cost of textbooks has become so high that I do not feel comfortable requiring students to purchase a textbook.
Thus, I created a textbook for this course.
The textbook for this course is available <u>for free</u> online:
https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook

Note: There is a section of the book that invites readers to donate to support its development.
**IMPORTANT**: This donation option is <u>*NOT*</u> for you.
The book is publicly available and the donation option is <u>intended for non-UI people</u> who use the book.
Per the [UI Policy Manual](https://opsmanual.uiowa.edu), faculty are prohibited from a) [receiving gifts from their students](https://opsmanual.uiowa.edu/community-policies/prohibition-giving-and-receiving-gifts) and b) [profiting from recommending or requiring the purchase of course materials from their students](https://opsmanual.uiowa.edu/human-resources/compensation/supplemental-activities-and-extra-compensation).
As described [here](https://opsmanual.uiowa.edu/human-resources/compensation/supplemental-activities-and-extra-compensation), "Faculty members who would otherwise receive royalties or other remuneration from the purchase of books or materials which they recommend or require in courses they teach should either refund the money to the students or make other arrangements to avoid profiting from their students' use of the materials (such as transferring it to the University or one of its units, or to the University of Iowa Center for Advancement)."
Bottom line: <u>**please do NOT donate or give other gifts—they are not allowed!**</u>

# Required Materials {#requiredMaterials}

For the class, you will be required to have access to a computer that allows you to install and run software (including `R`, `git`, and `GitHub Desktop`).
A laptop is preferable, so you can bring it to class and work through examples in class.

# Academic Honesty and Misconduct {#academicHonesty}

All students in CLAS courses are expected to abide by the [college's standards of academic honesty](https://clas.uiowa.edu/students/handbook/academic-fraud-honor-code).
Academic misconduct must be reported by instructors to CLAS according to [these procedures](https://policy.clas.uiowa.edu/clas-policies-and-procedures/undergraduate-education/academic-misconduct-undergraduate).
Please note that collaboration with other classmates on <u>quizzes, writing assignments, and during exams</u> is not permitted.
However, I do encourage you to collaborate with classmates to to learn `R`, statistics, and programming, and to *prepare* for exams (e.g., informal study groups).
Because writing, analytical, and critical thinking skills are part of the learning outcomes of this course, all work submitted by students should be prepared by the student.
Developing strong competencies in these domains will prepare you for a competitive workplace.
Therefore, AI-generated submissions are not permitted and will be treated as plagiarism.

# Course Requirements and Policies {#requirements}

## Lecture {#lecture}

We will meet two times weekly for lectures, at the time and location described [above](#lectureTime).
My powerpoint presentations for the lectures will be posted on [ICON](https://icon.uiowa.edu) no later than noon on the day before the lecture (though I may continue to refine the slides up until the time of lecture).
<u>Please note:</u> powerpoint presentations are an outline of my points. 
<u>It is your responsibility to take notes during class.</u>
If you have questions about the lecture notes or need clarification of any of the points, please ask in class or meet with Professor Petersen during office hours.
If you miss a lecture, get and review notes with a peer and watch the lecture recording.
Then, come to office hours if you have specific questions.

### Lecture Recordings {#recordings}

My intention is to record lectures so that you may review them.
Recorded lectures will be posted on the "UICapture" tab in [ICON](https://icon.uiowa.edu).
However, <u>please do not count on recordings being available</u>, in case I accidentally forget to initiate the recording or there is a technical malfunction.

## Attendance and Participation {#attendanceParticipation}

Attendance at lectures is required and will be factored into final grades (see grading section [below](#courseGrades)).
There are 29 lectures during the semester (excluding the examinations).
You will receive one point for attendance at each lecture up to 27 points (i.e., you will not receive extra credit for attending all 29 lectures).
<u>Thus, you will not be penalized for missing up to 2 lectures.
However, you will be responsible for learning any material missed for quizzes and exams, and I strongly encourage you to attend all lectures.
Poor lecture attendance is likely to affect the quality of students' work and success in the course.</u>

Students who miss <u>more than 2 lectures</u> due to participation in University activities must give the instructor a statement <u>before the absence</u> signed by a responsible official that specifies the dates and times the student will miss class.
Authorized activities include participation in athletic teams, the marching band or pep band, debate teams, and other recognized University groups, as well as participation in University field trips, service with the National Guard, and jury duty.
Absences due to illnesses or emergencies (that go over 2 lectures) must be documented with the University of Iowa [Absence Explanation Form](https://clas.uiowa.edu/faculty/student-attendance-and-absences) and sent to Professor Petersen within 48 hours of the absence.
Per university policy, if a student will be absent <u>5 or more consecutive days and the absence is due to illness or other emergency</u>, please contact the Registrar Service Center at (319) 384-4300 or registrar@uiowa.edu.

## Blog Articles {#blogArticles}

As part of the class, you will post blog articles (see the [course schedule](#outline) for deadlines).
<u>The blog articles are public</u>; <u>do not take this course if you do not feel comfortable posting blog articles with your full name in a public forum</u>.
There will be a penalty of 20% for all blog articles turned in late.
Your lowest score will be dropped.
A blog article is not considered "submitted" until you (a) post the blog article so that it is live and publicly available, AND (b) submit the assignment on [ICON](https://icon.uiowa.edu) with the URL link to your blog article.
All blog articles should be submitted to [ICON](https://icon.uiowa.edu) by 11:59 p.m. on the due date.

You are encouraged to submit your blog article <u>well before</u> the deadline.
<u>You can expect to run into technical issues</u> (e.g., errors when running your code, issues getting the blog post to compile etc.).
Thus, you should give yourself plenty of time to [troubleshoot](#troubleshooting) (see below) so that you can submit your blog article on time.

### Troubleshooting {#troubleshooting}

Sometimes code you write does not work.
That is okay; it happens to everyone.
Learning how to troubleshoot code is an important part of programming.
If you run into issues related to `R`, `GitHub`, `GitHub Pages`, or your code, here are a few pointers on how to get things working (as adapted from Luke Tierney):

- If you receive an error message, read what the message says.
Sometimes reading the error message is all it takes to figure out what the issue is and how to fix it.
- Read the whole error message: sometimes the most important part is at the beginning.
- If the message does not make sense to you, perform a Google search for the error/issue: often someone else has asked about the same issue and received a useful answer.
- Simplify your code.
    - Look carefully at intermediate results.
    - Replace complicated data by something smaller and simpler.
    - In the process you may find your mistake.
- Finding your bug usually involves double checking all the things you are sure you did right until you find the one you did not.

If you are unable to resolve things on your own, you may need to ask for help, in which case I encourage you to try one (or more) of the following:

- Perform a Google search for the error/issue
- Check the [Troubleshooting section](https://isaactpetersen.github.io/QuartoBlogFantasyFootball/posts/quarto-instructions/#sec-troubleshooting) of the course's Quarto Instructions
- Ask a peer
- Post on [forums dedicated to `R`](https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook/getting-started.html#sec-gettingHelpR)
- Come to office hours

I am quite busy, and I appreciate your making every effort to solve the issue on your own or using one of the aforementioned ways before emailing me.
I do not often respond to emails during evenings or weekends, and I cannot be expected to solve last-minute issues that you could have solved earlier.

## Readings & Quizzes {#readingQuizzes}

Readings and other materials (e.g., videos) will be posted on [ICON](https://icon.uiowa.edu).
You are expected to do the readings (and watch any required videos) before class.
You will have an online quiz on the readings/materials to complete in [ICON](https://icon.uiowa.edu), on your own, <u>before</u> each lecture.
The quizzes are meant to help you come to class prepared to contribute so you are best-positioned to learn and to help others learn.
The quizzes are not timed (you can spend as much time as you need on each quiz up until the deadline).
The deadline for each quiz is 30 minutes before class starts.
Late responses and multiple submissions will not be accepted.
Your lowest quiz score will be dropped.
We will not accept excused absences for quizzes because (a) you have a week to complete the quiz (and can submit it at any point during that week), and (b) we drop your lowest quiz score.
Each quiz will be weighted the same in the final grade.
Quiz answers will be viewable at the end of the week (i.e., after the last discussion section has taken their quiz).

Past experience has shown that in order to do well in this class, you should read the required material, participate actively in class, and go over your notes <u>each week</u>.
There is too much material being covered in this class to try to study only by frantic preparation immediately before exams.
Note that lecture will <u>not</u> cover all relevant material for the course; you will be expected to know the <u>required</u> readings for exams.

## Workload {#workload}

This is a 3 semester hour course.
Students should therefore expect to spend [6 additional hours per week](https://clas.uiowa.edu/faculty/student-workload-guidelines) (outside of class) reading the articles, reviewing material from lecture and discussion section, and preparing for quizzes and exams.

## Examinations {#exams}

There will be 2 exams; one mid-term exam and one non-cumulative final exam.
Each exam will emphasize information presented for the half of the class that precedes it.
However, some integration of information across sections will be required for questions on the second and third exams.
The exams will include multiple-choice questions.
Exam questions can come from <u>any of the following sources: lectures or required readings</u>.
For suggested study tips for this class, meet with Professor Petersen during office hours.

### Missing Exams {#missingExams}

[University regulations require that students be allowed to make up examinations](https://opsmanual.uiowa.edu/students/absences-class) that have been missed due to illness, religious holy days, military service obligations (including service-related medical appointments), or other unavoidable circumstances or University-sponsored activities.
Students with UI-authorized activities must discuss their absences with the instructor as soon as possible.
Religious obligations must be communicated within the first three weeks of classes.
See below for the documentation necessary for an absence to be excused and to be eligible to take a make-up exam.

Students are allowed to make up exams that have been missed due to illness, mandatory religious observations, official University activities, or other unavoidable circumstances.
Note: the format of the make-up exam may differ from the original exam.
If you know that you must be away at the time of an exam for one of these reasons, Professor Petersen must be contacted in advance whenever possible to schedule a make-up exam.
In order to take a make-up exam, you must provide acceptable documentation to be eligible to take it: including documentation for any report of illness; any other circumstances must be documented by the University of Iowa [Absence Explanation Form](https://clas.uiowa.edu/faculty/student-attendance-and-absences) and must be approved by Professor Petersen.
<u>In sum, to be eligible for a make-up exam, Professor Petersen must be contacted before the examination whenever possible, and you must send acceptable form of documentation to Professor Petersen</u>.

## Class Fantasy Football League {#fantasyFootballLeague}

As part of the class, we will have a fantasy football league.
The league will be composed of 10 teams, with approximately 2 students per team.
That is, you will (likely) be paired with another student in the class to co-manage a team.
The league will be hosted on [NFL.com](https://fantasy.nfl.com) and will follow [default NFL.com scoring settings](https://support.nfl.com/hc/en-us/articles/4989179237404-Scoring).
The league will be a head-to-head league, meaning that each week, your team will face one other team, and whichever team scores more points wins that week.
There are no course-related points based on your team's performance (i.e., you will NOT be punished for having a bad team); however, there is an [extra credit opportunity](#extraCredit) for winning the league.

The draft will be held during class time.
The draft will be a "snake" draft, meaning that the order of picks will reverse each round.
The draft order will be randomly determined.

In conjunction with your co-manager, you will make decisions regarding your team's name, draft picks, waiver wire pickups/drops, trades, and starting lineups.
Regardless of your expertise or experience with fantasy football, you and your co-manager are each 50% co-owners of the team.
That is, <u>you are expected to make all team-related decisions with your co-manager collaboratively</u>, not unilaterally.

As the commissioner of the league, I reserve the right to block any trades that that would compromise the integrity of the league.
Trades will be allowed as long as each team is acting in their team's best interests; that is, "lopsided" trades will be allowed as long as both teams are acting in good faith to improve their own team.
Trades will not be allowed if they involve collusion, that is, collaboration to cheat or deceive others.
Examples of collusion include:

- trading players for the purpose of improving the other team's standing in the league (and not your own)
- trading players who are not on bye week, just so an opponent can specifically beat another opponent and then trading those players back immediately
- trades that involve outside-of-the-game exchange of goods or services
- trades that involve a handshake agreement of in-game goods or services
- trades that cannot be completed in one trade

# Grading {#grading}

Final grades will be assigned at the end of semester on the basis of your total percentage of points earned on exams, quizzes, attendance, and writing assignments, as detailed below.
Grades will be assigned on an absolute scale (criterion-referenced grading); course grades will not be curved.
Please note: As a matter of fairness to all students, I assign grades based on performance and do not negotiate grades.
Final grades will be assigned based on the following ranges:

| Grade | Percent |
|:------|:--------|
| A+    | 97–100% | 
| A     | 93–96   |
| A−    | 90–92   |
| B+    | 87–89   |
| B     | 83–86   |
| B−    | 80–82   |
| C+    | 75–79   |
| C     | 70–74   |
| C−    | 65–69   |
| D+    | 60–64   |
| D     | 55–59   |
| D−    | 50–54   |
| F     | < 50%   |

I round up from .5 when determining final grades.
For example, a course percent of 79.50 would receive a B−, whereas a course percent of 79.49 would receive a C+.

# Course Grades {#courseGrades}

Final course grades will be assessed based on your performance in the activities below.
The relative contribution of each component to your final grade is as follows:

 - 25%	Examination #1
 - 25%	Examination #2 (administered only during the class's Final Exam time slot)
 - 10% 	Attendance/Participation
 - 10% 	Reading Quizzes
 - 30%  Writing Assignments

## Extra Credit {#extraCredit}

I will give you 0.5 point extra credit if you 1) identify an issue in the [course textbook](https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook) that needs to be fixed or 2) make a <u>specific</u> suggestion for a way to improve the [textbook](https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook) and its usefulness to you or other students.
For instance, to identify an issue that needs to be addressed, you could identify a typo, misspelling, grammatical issue, or (gasp), a mistake/error.
To receive the extra credit, [create a new issue](https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/issues) in the [textbook's GitHub repository](https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook), and email me after doing so.
I will give you an additional 0.5 point extra credit (for 1-point extra in total) if you implement the fixes/suggestions you specify.
To receive the extra credit for implementing the fix/suggestion, [create a pull request](https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/pulls) with your changes, and email me after doing so.
For instructions regarding how to create a pull request, see [here](https://devpsylab.github.io/DataAnalysis/git.html#pull-request).
If you are going to implement a change, I strongly encourage you to discuss with me before doing so, so I can verify that the change is worth implementing.
I reserve the right to determine whether the "fix", suggestion, or implementation warrants extra credit!
The extra credit must be completed by the last day of class.

In addition, the winner(s) of the [class fantasy football league](#fantasyFootballLeague) (whoever leads the league based on total points or win/loss record at the end of the class, i.e., week 14 of the NFL season) will get 1 point extra credit.
No additional extra-credit opportunities are available for this course.

# Tentative Course Outline (exam dates fixed) {#outline}

This is a *tentative* course outline.
Changes will be discussed in class.
There are 15 weeks in the semester, and class meets twice per week (30 sections).
We will have one exam during the semester and one final exam during finals week.

| **Section**      | **Day** | **Date** | **Content**                                                                  | Reading                             | Assignment                            |
|:-----------------|:--------|:---------|:-----------------------------------------------------------------------------|:------------------------------------|:--------------------------------------|
| [1](#section1)   | T       | 08/26    | Overview of Class; Overview of Fantasy Football                              | Ch 1–2                              | [CodeAcademy Module 1](https://www.codecademy.com/learn/learn-r) |
| [2](#section2)   | Th      | 08/28    | Statistical Programming: Using `R` for Statistical Analysis                  | Ch 3                                | [CodeAcademy Modules 2–3](https://www.codecademy.com/learn/learn-r) |
| [3](#section3)   | T       | 09/02    | Player Evaluation                                                            | Ch 6; Den Hartigh et al. (2018)     | **Set up blog; post welcome article** |
| [4](#section4)   | Th      | 09/04    | The Draft                                                                    | Ch 7; Lee & Liu (2022)              | [CodeAcademy Modules 5–6](https://www.codecademy.com/learn/learn-r) |
| [5](#section5)   | T       | 09/09    | Statistical Programming in `R`                                               | Ch 4                                | [CodeAcademy Modules 7–10](https://www.codecademy.com/learn/learn-r) |
| [6](#section6)   | Th      | 09/11    | Basic Statistics                                                             | Ch 8–9                              | **Blog article 1 due!**               |
| [7](#section7)   | T       | 09/16    | Data Visualization and Interpretation                                        | Ch 5; Schwabish (2021)              | [CodeAcademy Module 4](https://www.codecademy.com/learn/learn-r) |
| [8](#section8)   | Th      | 09/18    | Correlation Analysis                                                         | Ch 10; Goodwin & Leech (2006)       | **Blog article 2 due!**               |
| [9](#section9)   | T       | 09/23    | Multiple Regression                                                          | Ch 11; Osborne & Waters (2002)      |                                       |
| [10](#section10) | Th      | 09/25    | Mixed Models                                                                 | Ch 12; Brauer & Kurtin (2018)       |                                       |
| [11](#section11) | T       | 09/30    | Causal Inference                                                             | Ch 13; D'Onofrio et al. (2020)      | **Blog article 3 due!**               |
| [12](#section12) | Th      | 10/02    | Heuristics and Cognitive Biases in Prediction                                | Ch 14; Tversky & Kahneman (1974)    |                                       |
| [13](#section13) | T       | 10/07    | Human Judgment vs Actuarial Approaches to Prediction                         | Ch 15; Kahneman (2011), Ch 21 & 22  |                                       |
| [14](#section14) | Th      | 10/09    | Base Rates                                                                   | Ch 16; Kahneman (2011), Ch 14 & 30  | **Blog article 4 due!**               |
| [15](#section15) | T       | 10/14    | **Midterm Exam**                                                             |                                     |                                       |
| [16](#section16) | Th      | 10/16    | Evaluation of Prediction/Forecasting Accuracy: Binary Classification         | Ch 17 (Section 17.1–17.16.5)        |                                       |
| [17](#section17) | T       | 10/21    | Evaluation of Prediction/Forecasting Accuracy: Binary Classification         | Ch 17 (Section 17.6.6–17.6.8)       |                                       |
| [18](#section18) | Th      | 10/23    | Evaluation of Prediction/Forecasting Accuracy: Continuous Outcomes           | Ch 17 (Section 17.7–end of chapter) | **Blog article 5 due!**               |
| [19](#section19) | T       | 10/28    | Calibration Accuracy: Overconfidence Bias                                    | Kahneman & Tversky (1996); Massey & Thaler (2013) |                         |
| [20](#section20) | Th      | 10/30    | Machine Learning                                                             | Ch 19; Ramasubramanian & Singh (2019), Ch 6 | **Blog article 6 due!**       |
| [21](#section21) | T       | 11/04    | Mythbusters: Putting Fantasy Football Beliefs/Anecdotes to the Test          | Ch 18; White & Sheldon (2014)       |                                       |
| [22](#section22) | Th      | 11/06    | Modern Portfolio Theory                                                      | Ch 20; Chen (2016)                  | **Blog article 7 due!**               |
| [23](#section23) | T       | 11/11    | Cluster Analysis                                                             | Ch 21; Everitt et al. (2011)        |                                       |
| [24](#section24) | Th      | 11/13    | Factor Analysis                                                              | Ch 22; Field et al. (2012), Ch 17   | **Blog article 8 due!**               |
| [25](#section25) | T       | 11/18    | Data Reduction: Principal Component Analysis                                 | Ch 23                               |                                       |
| [26](#section26) | Th      | 11/20    | Simulation and the Monte Carlo Method                                        | Ch 24; Sigal & Chalmers (2016)      | **Blog article 9 due!**               |
|                  |         | 11/24–11/27 | **FALL BREAK – NO CLASSES**                                               |                                     |                                       |
| [27](#section27) | T       | 12/02    | Time Series Analysis                                                         | Ch 25; Hyndman & Athanasopoulos (2021), Ch 1 (through Section 1.7) |        |
| [28](#section28) | Th      | 12/04    | Decision Making in the Context of Uncertainty                                | Ch 26; Larrick et al. (2024)        | **Blog article 10 due!**              |
| [29](#section29) | T       | 12/09    | Sports and Cognitive Psychology: Coaching and Risk Aversion                  | Ch 27; Moskowitz & Wethheim (2012), Ch 3 & 16 |                             |
| [30](#section30) | Th      | 12/11    | Sports and Cognitive Psychology: Psychological Factors in Player Performance; Expert Performance and Automaticity | Ch 27; Moskowitz & Wethheim (2012), Ch 17 | **Blog article 11 due!**       |
| Finals Week      |         | TBD (week of 12/15) | **Final Exam**                                                    |                                     |                                       |

# Date and Time of the Final Exam {#finalExam}

The [final examination date and time](https://registrar.uiowa.edu/final-exam-schedules) will be announced by the Registrar generally by the fifth week of classes, and it will be announced on the course ICON site once it is known.
<u>Do not plan your end of the semester travel plans until the final exam schedule is made public.
It is your responsibility to know the date, time, and place of the final exam.</u>
According to Registrar's final exam policy, students <u>have a maximum of two weeks after the announced final exam schedule</u> to request a change if an exam conflict exists or if a student has more than two exams in one day (see the [policy](https://registrar.uiowa.edu/makeup-final-examination-policies) here).

# Course Resources {#courseResources}

There are many course resources available to help you succeed in the class, including:

- Powerpoint slides for lecture
- getting and reviewing missed notes from a peer
- [lecture recordings](#recordings)
- the [course textbook](https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook) and assigned readings
- review your reading quizzes and the answers
- instructor office hours
- peer study groups
- Tutor Iowa: https://tutor.uiowa.edu

# Drop Deadline for this Course {#dropDeadline}

You may drop an individual course before the drop deadline; after this deadline you will need collegiate approval.
You can look up the drop deadline for this course [here](https://registrar.uiowa.edu/course-deadlines).
When you drop a course, a "W" will appear on your transcript.
The mark of "W" is a neutral mark that does not affect your GPA.
To discuss how dropping (or staying in) a course might affect your academic goals, please contact your Academic Advisor.
Directions for adding or dropping a course and other registration changes can be found on the [Registrar's website](https://registrar.uiowa.edu/change-registration-myui).
Students can find policies on dropping CLAS courses [here](https://clas.uiowa.edu/students/students-academic-policies/registration-policies#dropping).
Students should adhere to the [academic deadlines](https://grad.uiowa.edu/academics/deadlines) and policies set by the Graduate College.

# Feedback about the Course {#feedback}

I welcome feedback at any point during the class.
If you have comments on the class or my teaching, please feel free to meet with me during office hours.

## Student Complaints {#complaints}

Students with a complaint about a grade or a related matter should first discuss the situation with the instructor, finally with the DEO (Chair) of the department, school or program offering the course.
Sometimes students will be referred to the department or program's Director of Undergraduate Studies (DUS) or Director of Graduate Studies (DGS).
Students should contact [CLAS Undergraduate Programs](https://clas.uiowa.edu/students/handbook/student-rights-responsibilities#rights) for support when the matter is not resolved at the previous level.

# Communication: UI Email {#email}

Students are responsible for all official correspondences sent to their UI email address (uiowa.edu) and must use this address for any communication with instructors or staff in the UI community.
For the privacy and the protection of student records, UI faculty and staff can only correspond with UI email addresses.

## Other Expectations of Student Performance {#otherExpectations}

Students have the right to a distraction-free learning environment.
You have the responsibility to help create such a classroom environment.
Please treat other students in the class and the instructor with respect.
Students are expected to help each other learn and to contribute overall to the learning environment of the course.
Arriving prepared for class is part of this expectation.

# University Policies {#UIowaPolicies}

[University Policies](https://provost.uiowa.edu/student-course-policies)

[Accommodations for Students with Disabilities](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#accommodations-for-students-with-disabilities)\
The University is committed to providing an educational experience that is accessible to all students.
If a student has a diagnosed disability or other disabling condition that may impact the student's ability to complete the course requirements as stated in the syllabus, the student may seek accommodations through [Student Disability Services](https://sds.studentlife.uiowa.edu/students) (SDS).
SDS is responsible for making Letters of Accommodation (LOA) available to the student.
<u>The student must provide an LOA to the instructor as early in the semester as possible, but requests not made at least two weeks prior to the scheduled activity for which an accommodation is sought may not be accommodated.</u>
The LOA will specify what reasonable course accommodations the student is eligible for and those the instructor should provide.

- [Free Speech and Expression](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#free-speech-and-expression)
- [Non-Discrimination](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#non-discrimination-statement)
- [Accommodations for Students with Disabilities](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#accommodations-for-students-with-disabilities)
- [Absences from Class](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#absences-from-class)
- [Absences for Religious Holy Days](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#absences-for-religious-holy-days)
- [Absences for Military Service Obligations](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#absences-for-military-service-obligations)
- [Classroom Expectations](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#classroom-expectations)
- [Sexual Harassment/Misconduct and Supportive Measures](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#sexual-harassment--sexual-misconduct-and-supportive-measures)
- [Conflict Resolution](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#conflict-resolution)
- [Mental Health](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#mental-health)
- [Basic Needs and Student Support](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#basic-needs-and-student-support)
- [Sharing of Class Recordings](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#sharing-of-class-recordings-if-appropriate)

# Where to Get Academic Support for This Course {#academic-support}

- Drop-in study groups and one-on-one tutoring: drop-in student hours of the <u>undergraduate TA, graduate TA, and</u> instructor
- Formal tutoring: Tutor Iowa: https://tutor.uiowa.edu
- UI Writing Center: https://writingcenter.uiowa.edu
- Academic accommodations: https://sds.studentlife.uiowa.edu

# Mental Health Resources and Student Support {#mental-health}

Students are encouraged to be mindful of their mental health and seek help as a preventive measure or if feeling overwhelmed and/or struggling to meet course expectations.
Students are encouraged to talk to their instructor for assistance with course-related concerns.
For additional mental health support, please see the guidance and resources at [mentalhealth.uiowa.edu](http://mentalhealth.uiowa.edu), including the 24-7 [UI Support and Crisis Line](https://mentalhealth.uiowa.edu/ui-support-and-crisis-line).  

Additionally, the Office of the Dean of Students can help students navigate personal crisis situations.
They can provide one-on-one support, help with identifying options, and access to [basic needs resources (such as food, rent, childcare, etc.)](http://basicneeds.uiowa.edu).
Student Care and Assistance: 132 IMU, [dos-assistance@uiowa.edu](mailto:dos-assistance@uiowa.edu), or 319-335-1162 and more info: [dos.uiowa.edu/assistance](https://dos.uiowa.edu/assistance)

If you feel that you or someone you know may be struggling with an academic, emotional, or psychological problem, the following organizations are available for assistance:

| Service                                                                    | Contact Info                                                     |
|:---------------------------------------------------------------------------|:-----------------------------------------------------------------|
| University of Iowa Academic Advising Center                                | 353-5700, https://advisingcenter.uiowa.edu                       |
| University Counseling Services                                             | 335-7294, https://www.uiowa.edu/ucs                              |
| Student Health Service - Mental Health                                     | 335-8394, https://studenthealth.uiowa.edu/services/psychiatry    |
| University of Iowa Hospitals and Clinics Adult Psychiatry Services Clinic  | 353-6314, https://www.uihealthcare.org/Psychiatry                |
| Seashore Clinic (in the UI Department of Psychological and Brain Sciences) | 335-2467, https://psychology.uiowa.edu/resources/seashore-clinic |
| Women's Resource and Action Center                                         | 335-1486, https://wrac.uiowa.edu                                 |
| Rape Victim Advocacy Program                                               | 319-335-6000 or 800-228-1625, https://www.uiowa.edu/~rvap        |
| Office of Sexual Misconduct                                                | 319-335-6200, https://osmrc.uiowa.edu                            |
| CommUnity                                                                  | 855-325-4296, https://builtbycommunity.org/crisis                |
| Community & Family Resources                                               | 351-4357, https://www.cfrhelps.org/                              |

<u>If you or someone you know is contemplating suicide</u>, either call or text the Suicide and Crisis Lifeline at 988, or call 911.

# Disclosures {#disclosures}

I am the Owner of Fantasy Football Analytics, LLC, which operates https://fantasyfootballanalytics.net.
I do not require or encourage students to use my website, and I do not promote or endorse any specific content or services offered by Fantasy Football Analytics.

# Disclaimer {#disclaimer}

"*This material probably won't win you fantasy football championships.
You could take what we learn and apply it to fantasy football and you might become 5 percent more likely to win.
Or...
Consider the broader relevance of this.
You could learn data analysis and figure out ways to apply it to other systems.
And you could be making a six-figure salary within the next five years.*"
– Benjamin Motz, Ph.D.

This syllabus is subject to change.
Any changes will be discussed in class, via email, and/or on ICON.
